import React, { useState } from 'react';
import './ModelGenerator.css';

export default function ModelGenerator() {
  const [imageSrc, setImageSrc] = useState(null);
  const [modelUrl, setModelUrl] = useState(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState(null);

  const handleImageUpload = (e) => {
    const file = e.target.files[0];
    if (!file) return;

    const reader = new FileReader();
    reader.onload = (event) => {
      setImageSrc(event.target.result);
      setModelUrl(null);
      setError(null);
    };
    reader.readAsDataURL(file);
  };

  const handleGenerate = async () => {
    if (!imageSrc) return;
    setLoading(true);
    setError(null);

    try {
      const base64Data = imageSrc.split(',')[1];

      // Try localhost instead of 127.0.0.1 for better browser compatibility on some systems
      const response = await fetch('http://localhost:8081/generate', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({ 
          image: base64Data,
          guidance_scale: 5.0,
          num_inference_steps: 20
        }),
      });

      if (!response.ok) {
        const errData = await response.json().catch(() => ({}));
        throw new Error(errData.text || `Server error: ${response.status}`);
      }

      const blob = await response.blob();
      const objectUrl = URL.createObjectURL(blob);
      
      setModelUrl(objectUrl);
    } catch (err) {
      console.error(err);
      setError(err.message || 'An unknown error occurred during generation.');
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="generator-container">
      <div className="generator-card">
        <h2 className="generator-title">🪄 Imagine in 3D</h2>
        <p className="generator-subtitle">Upload any image to turn it into a high-fidelity 3D model.</p>

        <div className="upload-section">
          <label className="file-upload-label">
            <input 
              type="file" 
              accept="image/png, image/jpeg, image/webp" 
              onChange={handleImageUpload} 
            />
            {imageSrc ? 'Change Image' : 'Choose an Image'}
          </label>
        </div>

        <div className="workspace-area">
          {imageSrc && !modelUrl && (
            <div className="preview-container">
              <img src={imageSrc} alt="Source Preview" className="uploaded-preview" />
            </div>
          )}

          {modelUrl && (
             <div className="result-container">
               <div className="viewer-wrapper">
                 <model-viewer 
                   src={modelUrl}
                   alt="A 3D model generated by Hunyuan3D"
                   auto-rotate
                   camera-controls
                   shadow-intensity="1"
                   environment-image="neutral"
                   exposure="1.0"
                 ></model-viewer>
               </div>
             </div>
          )}
        </div>

        {error && <div className="error-message">{error}</div>}

        <button 
          className={`generate-btn ${loading ? 'generating' : ''}`}
          onClick={handleGenerate}
          disabled={!imageSrc || loading}
        >
          {loading ? (
            <>
              <span className="spinner"></span> Synthesizing 3D...
            </>
          ) : (
            'Generate 3D Model'
          )}
        </button>
      </div>
    </div>
  );
}
